### ISSUE TITLE
Response Code

### ISSUE THREAD

**Issue by sonewman** [stevenjackson/pinch_hitter#2]
Hi, I am a bit of a noob with this, but it looks like there isn't a clear way to set a response code for an endpoint request. I was thinking I could maybe do it with RegisterModule, but it looks like it only allows the `message` to be sent back.

**Comment by stevenjackson** [comment]
Yes, that's a bit outside the original idea for this (stand-in for a third party service that works reliably in production but not in a test environment).  What's your use case?  Maybe we can figure something out.

**Comment by sonewman** [comment]
We were just keen to use it for mocking for testing a bridge API we are working on. 
But i think in order to facilitate it it would likely involve a breaking change.

Essentially `handler.respond_to` would need to pass back a response object rather than just the message body since we actually require the mocking of response codes and headers.

**Comment by stevenjackson** [comment]
If you're ok with the module hydrating a full response object, then I'm pretty sure I can make it work without breaking anything.  If nothing else I can give you a branch to start from: you can fork and make it your own.

**Comment by sonewman** [comment]
I'm happy to fork, at the time I hadn't looked at the code thoroughly enough, if there is simple way to facilitate that then i'd certainly be happy with it :smile:

**Comment by stevenjackson** [comment]
Ok, here's a rough cut at my idea:

You register a module just like before.  Instead of `respond_to` it should have a `handle_request(request, response)` method.  `handle_request` will receive the request (a hash with :body and :headers keys) and the [Sinatra::Response](http://www.rubydoc.info/github/sinatra/sinatra/Sinatra/Response) object.  

The handler will be responsible for hydrating the response and returning it.  You can see a very crude example in this [test](https://github.com/stevenjackson/pinch_hitter/blob/6d033f6c56587c8c98033db07da7d9d20a9be3f5/test/test_service.rb#L146).

To test with this (I hope you're using Bundler), just replace your normal pinch_hitter line with:

```
gem 'pinch_hitter', :git => 'https://github.com/stevenjackson/pinch_hitter.git', :branch => 'with_headers'
```

If you're happy with it, I'll do some refactoring and docs and roll a new release.  I'm open to suggestions on either the request or response object; I went with the path of least resistance on both.

Let me know if it works!

**Comment by sonewman** [comment]
this looks like it could work, I will have a play see how i get on. Thanks! :+1:

**Comment by stevenjackson** [comment]
@sonewman Did this work out for you?

**Comment by sonewman** [comment]
no not really, it seemed to make my previously passing test fail, i'm not sure why. So i just wrote a thin wrapper around Sinatra instead. Sorry I didn't get back to you.

**Comment by stevenjackson** [comment]
No problem, glad you didn't get stuck.  I'll close this out unless there's a reason to pick it up again.

**Comment by sonewman** [comment]
Cool, thanks for you help anyways I appreciate you getting back to me :smile:
